[server]
address = "0.0.0.0"
headless = true
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = false
maxUploadSize = 5120
maxMessageSize = 5120

[browser]
gatherUsageStats = false
