[server]
address = "0.0.0.0"
port = 8501
maxUploadSize = 5120
maxMessageSize = 5120
headless = true
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
